namespace "spec" do
  desc "Run simple specs"
  task :simple do
    sh "bin/simple_test_runner.rb simple_tests"
  end

  task :perf do
    sh "bin/simple_test_runner.rb perf_tests"
  end

  desc "Run rubyspec language specs"
  task :language do
    sh "time mspec/bin/mspec ci -f specdoc :language"
  end
end
task :spec => ["spec:simple", "spec:language"]

task :default => [:spec]
